name: deploy

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 17
        cache: yarn
    - run: yarn
    - run: yarn run lint

  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    # Runs a remote script via SSH
    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd ThonkBot
          ./deploy.sh