name: linting

on: pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 17
        cache: yarn
    - run: yarn
    - run: yarn run lint