name: Pull requests

on: pull_request

jobs:
  lint:
    name: lint and transpile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # https://stackoverflow.com/a/62244232/10992079
      - name: Install project dependencies
        run: yarn --prefer-offline
      - name: run lint
        run: yarn run lint
      - name: tsc
        uses: icrawl/action-tsc@v1

  version-check:
    name: Version check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Determine version
        id: version-check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
      - name: Fail if version wasn't updated
        if: steps.version-check.outputs.changed == 'false'
        run: exit 1